### ISSUE TITLE
Tickets status has effect only on HTML output 

### ISSUE THREAD

**Issue by paramir** [slimndap/wp-theatre#112]
Hey there! 
When using the tickets() function with the HTML argument set to false, the function will always return the tickets URL. It can be handy to check (at least) for cancelled status and return false or a "cancelled" string. Just an idea :)

**Comment by slimndap** [comment]
You are right, that would be more appropriate. 
It think this function is up for a major rewrite anyway.

**Comment by paramir** [comment]
sounds great :)

**Comment by slimndap** [comment]
Let me know if you have any other ideas about this particular feature. 



—
Slim & Dapper
http://slimndap.com

**Comment by slimndap** [comment]
`WPT_Event::tickets()` now returns an empty string for cancelled events.
