### ISSUE TITLE
Events don't display on production page.

### ISSUE THREAD

**Issue by bioforellen** [slimndap/wp-theatre#126]
After the upgrade, the production pages don't list the events.

Example: http://www.bioforellen.se/max/production/insidan-ut/

**Comment by slimndap** [comment]
Hi! If I go to this page now, I can still see the events:
![screen shot 2015-06-05 at 22 13 39](https://cloud.githubusercontent.com/assets/2284714/8014359/52301c26-0bd0-11e5-93dd-42a4bbd64d5c.png)

Or do you mean something different?

**Comment by slimndap** [comment]
@bioforellen 

Is the problem still there?

**Comment by bioforellen** [comment]
Hi,

Yes. I had to paste the shortcode in order to make it work.
/Marcus



Den den 16 juni 2015 klockan 11:35 skrev Jeroen Schmit
<notifications@github.com>:

> 
> @bioforellen <https://github.com/bioforellen>
> 
> Is the problem still there?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/slimndap/wp-theatre/issues/126#issuecomment-112364525>
> .
> 
> 


Med vänlig hälsning

Marcus Löwin
Webmaster Tyresö Filmförening
www.bioforellen.se

Biograf Forellen
Tyresö Centrum

**Comment by slimndap** [comment]
Ok, cool.
