### ISSUE TITLE
Eventpages not working due to new translation necessary?

### ISSUE THREAD

**Issue by osvans** [slimndap/wp-theatre#130]
Hi!

I noticed after updating the plugin my event pages woren't working anymore. The links to the events used to be www.website.nl/productie/eventname but now the were www.website.nl/production/eventname. So english instead of dutch. 

I've translated the lowest entry in this screenshot, which wasn't translated, to "productie" and now it's woking again.

![schermafbeelding 2015-06-16 om 10 56 35](https://cloud.githubusercontent.com/assets/7955779/8179448/faa28378-1416-11e5-8be5-dbdbb4ca9a0c.png)

**Comment by slimndap** [comment]
Thank you! I will fix this in the next minor update.

Good to know: this part of the plugin with get a big overhaul in the next major update. See #119.

**Comment by osvans** [comment]
👍
