### ISSUE TITLE
List events grouped by production

### ISSUE THREAD

**Issue by jbrandligt** [slimndap/wp-theatre#137]
This is useful for productions with multiple events belonging together. Another approach would be to have multiple day events, but I think that might be a little harder to implement and there is already an issue for this (#42).

**Comment by slimndap** [comment]
Could this extensions be the solution?
http://theater.slimndap.com/downloads/timetable-for-theater/

**Comment by jbrandligt** [comment]
I'm not sure, I created my own table layout to list the events, which fits
exactly to my needs. The grouping by productions looks good though. I will
check it out, thanks for the tip.

2015-09-11 15:36 GMT+02:00 Jeroen Schmit <notifications@github.com>:
