### ISSUE TITLE
filtering issue in admin

### ISSUE THREAD

**Issue by jbrandligt** [slimndap/wp-theatre#142]
There seem to be an issue with filtering productions in the admin interface: 
- when filtering productions on category results in an empty list.

Could be something wrong with my site, but something is not quite right. I will do more testing and try to find out what exactly is wrong.

**Comment by slimndap** [comment]
Can you be more specific?

How exactly are you filtering productions in the admin?

**Comment by jbrandligt** [comment]
When I am in the admin interface on the page where the productions are listed and I select a category from the drop-down list and click on Filter to show only the productions belonging to that category, the page returns empty.

**Comment by slimndap** [comment]
Not able to reproduce this.

I tried this:

1. Create three productions with upcoming events. 
1. Put two of the production in the 'cabaret' category.
1. Go to the productions page in de the admin.
1. Choose 'cabaret' in the category dropdown and clikc on 'filter'.

I then see the two productions:

![screen shot 2015-07-02 at 12 04 33](https://cloud.githubusercontent.com/assets/2284714/8474738/89daaae6-20b2-11e5-8710-d440188c1ee5.png)

**Comment by jbrandligt** [comment]
Strange, that is exactly what I do.... Could this be theme related too? I will do some more testing to see what causes this behaviour.

**Comment by jbrandligt** [comment]
Well, I never would have guessed it, but this also seems to be related to the theme. Next time I run into an issue I will blame the theme first!
