### ISSUE TITLE
wpt_productions css issue

### ISSUE THREAD

**Issue by jbrandligt** [slimndap/wp-theatre#143]
When applying a filter to [wpt_productions], the first production in the result list is not displayed. Instead there is a white space/area. I tried with cat, category_name and post__in filters. Results where the same, the first production is not displayed.

**Comment by jbrandligt** [comment]
The production is there in the html, but just not displayed, so it is a css issue.

**Comment by slimndap** [comment]
How can I reproduce this?

I don't see it when I do this:

1. Publish two production with a 'cabaret' category and an upcoming event.
1. Use the built-in Theater css.
1. Use `[wpt_productions category_name="cabaret"]` on a page.

When I view the page I see both productions.

**Comment by jbrandligt** [comment]
I think it is the theme I'm using what's causing the problem. Sorry for the confusion, you can close the issue. I'll have to figure out how to fix this in the theme, thanks.
