### ISSUE TITLE
Event don't showed on page

### ISSUE THREAD

**Issue by Tibwo** [slimndap/wp-theatre#163]
Hi, 
Probleme with appearance of the events on the page i haved choose. Same for the widget.
The settings are good...
Thx for helping ! :)

**Comment by slimndap** [comment]
Hi Tibwo!

I need some more information in order to help you.
1. What are the exact settings on Theater / Settings / Display?
1. What are the event dates of the productions that should appear?
1. What is the post status of the productions that should appear?

Jeroen

**Comment by Tibwo** [comment]
Hi Jeroen,

Thanks for your answer, i just checked the date and it was past, so that's
why it didn't appear ! Always a little thing...

Thanks again !
Have a good day !

Thibault MUSA
--
Consultant Webdesigner
thibault.musa@gmail.com
www.thibaultmusa.com
+1514-431-4843 / +33676562356

2015-08-22 5:43 GMT-04:00 Jeroen Schmit <notifications@github.com>:

**Comment by slimndap** [comment]
Cool. Can't wait to see what you create with it.
