### ISSUE TITLE
Sorting productions manually

### ISSUE THREAD

**Issue by paramir** [slimndap/wp-theatre#169]
hey Jeroen, I need to list the productions on the homepage in a user defined order. for this I have been using the Intuitive Custom Post Order plugin which works fine. the only problem as of recently is that on the admin page the productions always sort according to the Speeldata column. I was working with a pre_get_posts filter:
```
if ( is_admin() ) {
	if( is_post_type_archive('wp_theatre_prod') ) {
		$query->set( 'orderby', 'menu_order' );
	}
	return $query;
}
```
but it seems not to work anymore... to make a little more complicated, I have a "status" custom field added to productions, and the user can filter the productions according to the status. so, to sum it up: the user can go to the productions list, filter them on "huidige seizoen" status and then drag them around to decide the order. all fine. it also shows on the homepage as it is supposed to. the problem starts when the user revisits the same filtered results page: productions are again in the "wrong" order (speeldata) and the user needs to resort them again :(
Could you help me out here?

**Comment by slimndap** [comment]
I can look into it later, but what happens if you set the priority of your action to a really high number (eg. 99)?

**Comment by slimndap** [comment]
If that doesn't fix it, can you give me the full code, including the `add_action()` statement?

**Comment by paramir** [comment]
Ok, I'll give it a try! 

Ehud Neuhaus 
(on the go)

**Comment by slimndap** [comment]
Did it work?

**Comment by slimndap** [comment]
Ehud!

**Comment by paramir** [comment]
hi Jeroen!

i’m sorry for not responding, I was deadlining :)
the problem was actually with my pre_get_posts code and not with the plugin, so this is resolved. 
thank you for your help!

ciao,
Ehud
