### ISSUE TITLE
Schema.org tags to events

### ISSUE THREAD

**Issue by ovans** [slimndap/wp-theatre#175]
Is it possible to add schema.org tags to the events?

**Comment by slimndap** [comment]
I'm working on an extension that adds this.
I already have it working on this website:
http://www.theaterzuidplein.nl/

I will let you as soon as it's available.

**Comment by slimndap** [comment]
Related issue: #92.

**Comment by slimndap** [comment]
This is now available as a separate extension:
http://theater.slimndap.com/downloads/rich-snippets-theater/
