### ISSUE TITLE
Add ability to save venue(s)

### ISSUE THREAD

**Issue by ngates87** [slimndap/wp-theatre#186]
Most of the time my groups production are all at the same place, or a few reoccurring ones, it would be nice if the plugin could store those, and let me pick in a simple drop drown when setting up production dates.

**Comment by slimndap** [comment]
Here is some code that adds this funcitonality:
https://gist.github.com/slimndap/ea7b9a6d07b2f992831b

The only thing is that you have to add your venue options to the code.
