### ISSUE TITLE
Production with multiple events in error

### ISSUE THREAD

**Issue by tomaszkoziara** [slimndap/wp-theatre#187]
When I try to save a production with two or more events I get an error on wpt_admin.php line 334 and 335. There are two variables named $post with different meanings. I fixed it by changing the name of the array $post variable in $post_for_update.

Then I found out a second error in the production admin table, it is on wpt_listing_page.php on line 553. I fixed it simply by checking in the if condition if $this->page() is null.

**Comment by slimndap** [comment]
Thanks! If you like you can create a pull request so you receive the proper credits.

**Comment by tomaszkoziara** [comment]
Ok I did it. I only fixed the first problem because the second one doesn't exist in the code from GitHub. Maybe the plugin version downloaded from Wordpress isn't up to date?

**Comment by slimndap** [comment]
I just released 0.14.3 that contains your fix. Welcome to the club: https://github.com/slimndap/wp-theatre/graphs/contributors

I guess I already had a fix for the seconds problem ready.

**Comment by tomaszkoziara** [comment]
Thank you very much! 😃
Ok, I'll try it this evening.

2016-02-15 9:44 GMT+01:00 Jeroen Schmit <notifications@github.com>:

> I just released 0.14.3 that contains your fix. Welcome to the club:
> https://github.com/slimndap/wp-theatre/graphs/contributors
>
> I guess I already had a fix for the seconds problem ready.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/slimndap/wp-theatre/issues/187#issuecomment-184115053>
> .
>



-- 
Tomasz Koziara
