### ISSUE TITLE
Edit Event Detail Template

### ISSUE THREAD

**Issue by hlorridi** [slimndap/wp-theatre#191]
How can we edit the event details page (to display price & co)?

**Comment by slimndap** [comment]
There are several options. 

## Without writing code

1. Go to Theater → Settings → Display.
1. Scroll down to 'Events on production pages'.
1. Select 'show above content'.
1. Optionally, add a template. See the [documentation](https://github.com/slimndap/wp-theatre/wiki/Shortcodes#template) for some examples.

Another option is to add the 'Theater Production Events' widget to your event page.

## With writing code
Duplicate the `single.php` file of your template and name it `single-wp_theatre_prod.php`.
WordPress now uses this file to display the event details page. You can change it to do whatever you like.
