### ISSUE TITLE
After bulk publish the sort order on the admin screen is incorrect

### ISSUE THREAD

**Issue by mennolui** [slimndap/wp-theatre#198]
Normally productions are sorted on start date. After bulk publishing multiple screens with draft productions (upcoming only), the sort order on the admin screen is incorrect. After viewing the upcoming events on the front end of the website, the sort order on the admin screens was back to normal.

**Comment by slimndap** [comment]
Can you check if this is still the cases if you update to 0.15.5. I may be related to #197.

**Comment by mennolui** [comment]
Not fixed. Tested with 0.15.6 and a fresh import, 3 admin pages filled with productions.

After bulk publishing admin page 1 and page 3 the sort order was: all the published productions followed by all remaining draft productions. After bulk publishing 1 of the remaining draft production, it moved to position 2 on the first page, right after the only past production.

Sort order is corrected when waiting a couple of minutes.
