### ISSUE TITLE
WPT_Productions::get() returns productions with upcoming events when using end='now'

### ISSUE THREAD

**Issue by mennolui** [slimndap/wp-theatre#202]
`WPT_Productions::get()` calls `WPT_Productions::get_productions_by_date()` when `start` or `end` is specified. This function returns all productions that have at least one event that matches the `start` and `end` args.

I expected the function to return only productions where all events match the args. Eg. I expected productions where all events are in the past when using `end='now'`.

See:
https://github.com/slimndap/wp-theatre/blob/master/functions/wpt_productions.php#L737

Maybe this is desired behaviour, and documentation could explain this.

**Comment by slimndap** [comment]
Same as #210?
