### ISSUE TITLE
Productions cannot be sorted

### ISSUE THREAD

**Issue by tribut** [slimndap/wp-theatre#239]
It seems that `[wpt_productions order="asc"]` and `[wpt_productions order="desc"]` result in the exact same listing. If I understand the code correctly, the productions are supposed to be sorted according to `_wpt_order`, but there is no way to change that value as far as I could discover.
Sort order plugins seem to only be able to sort seasons, never productions.

**Comment by tribut** [comment]
This apparently only happens, when productions have no events. I'll assign some bogus events to past productions to fix the sorting.

**Comment by slimndap** [comment]
I think you're right.
Productions are ordered by the starttime of their first upcoming events. So the `order` param does not have any effect if there are no upcoming events.

**Comment by tribut** [comment]
Ordering seems to work here, even if the events are in the past.
