### ISSUE TITLE
wpt widget fails in combination with Elementor

### ISSUE THREAD

**Issue by RaymondVanMelzen** [slimndap/wp-theatre#246]
Hi Jeroen,

After upgrading to 0.15.24 I get the following error on a page containing the wpt widget:

Fatal error: Call to a member function get() on null in /public/sites/dev.branoul.nl/wp-content/plugins/theatre/functions/wpt_widget.php on line 38

Updating to 0.15.25 does not resolve the issue.

The widget is placed on a page that is styled with Elementor

http://dev.branoul.nl/productie/salon-branoul-platero-en-ik/

![image](https://cloud.githubusercontent.com/assets/29004359/26523464/6dd69690-4318-11e7-86cb-cc0a21de53dd.png)

**Comment by slimndap** [comment]
Can't believe I missed that. A fix will be out shortly.

**Comment by RaymondVanMelzen** [comment]
Thank you for fixing this so rapidly! After updating the widget works as expected.

Regards,
Raymond
