### ISSUE TITLE
Feature request: shortcode template code for printing out the tags

### ISSUE THREAD

**Issue by RaymondVanMelzen** [slimndap/wp-theatre#247]
Could you please add a shortcode template code for printing out the tags of a production.

eg. `[wpt_events limit="1" category_name="Uitgelicht"]{{tags}}[/wpt_events]`

Regards,
Raymond

**Comment by slimndap** [comment]
Are you a developer? Would you be able to add this yourself (with some help of me)?

**Comment by RaymondVanMelzen** [comment]
I could always try. How would I go about adding a field?

**Comment by RaymondVanMelzen** [comment]
Hi Jeroen,

I managed to copy the logic for {{categories}} and adapt it for {{tags}}. I am not familiar with github, though.  Should I post my edits here somewhere?

Regards,
Raymond

**Comment by RaymondVanMelzen** [comment]
Hi Jeroen,

After some reading I installed git, cloned theatre and staged the changes I made. Should I commit or is the a sort of reviewprocess?

Regards,
Raymond

**Comment by slimndap** [comment]
Raymond,

You need to create a pull request:
https://help.github.com/articles/creating-a-pull-request/

I will then review your commit, we can discuss it and when everything is
fine, I can merge it into the project.

Op di 30 mei 2017 om 14:57 schreef Raymond van Melzen <
notifications@github.com>:

**Comment by slimndap** [comment]
Added in v0.15.27.
