### ISSUE TITLE
wpt_event.php city filter

### ISSUE THREAD

**Issue by msennapv** [slimndap/wp-theatre#254]
in the function city() of wpt_event.php I think the first apply_filters() parameter is wrong.

the code:
if ( ! isset( $this->city ) ) {
			$this->city = apply_filters( '**wpt_event_venue**',get_post_meta( $this->ID,'city',true ),$this );
		}

should be:
if ( ! isset( $this->city ) ) {
			$this->city = apply_filters( '**_wpt_event_city_**',get_post_meta( $this->ID,'city',true ),$this );
		}

**Comment by slimndap** [comment]
I think you are right!

If you like, you can create a pull request to receive the proper credits as a contributor.

**Comment by msennapv** [comment]
Thank you, I'll do.  I'm new to github, still learning :)

**Comment by slimndap** [comment]
This should get you started:
https://help.github.com/articles/creating-a-pull-request/
