### ISSUE TITLE
season argument not working

### ISSUE THREAD

**Issue by WalterMuschenheim** [slimndap/wp-theatre#257]
#144 
[wpt_productions] shows all productions.

[wpt_productions season="2017"] shows nothing.

same for [wpt_productions_timetable season="2017"]

It looks like this bug was reported and marked as resolved, but it is still happening.

**Comment by slimndap** [comment]
You need to enter the season's `ID` in the `season` parameter.

**Comment by WalterMuschenheim** [comment]
Great, thanks for the help.
