### ISSUE TITLE
archive function in backend

### ISSUE THREAD

**Issue by Tonistroubles** [slimndap/wp-theatre#267]
It would be a cool feature to be able to archive events easily in backend. For instance if a season ends to just archive that season so you don't get an endless amount of pages in backend and things are a but more organised.

Pages would still exist in frontend, to make sure we don't get 404's all over the place. But you can start with a clean slate in backend. Archive should still be browsable and archived events still to be duplicated.

**Comment by slimndap** [comment]
I was thinking to improve the fiiltering option at the top of the events screen:

Current situation:

<img width="1147" alt="screen shot 2018-01-18 at 15 00 07" src="https://user-images.githubusercontent.com/2284714/35101568-51b5f35a-fc60-11e7-8214-5fef3f4ff90e.png">

We could add some dropdown that would allow you limit the list to upcoming or past event, or categories. Just like the posts screen:

<img width="1151" alt="screen shot 2018-01-18 at 15 03 01" src="https://user-images.githubusercontent.com/2284714/35101694-b7a88e20-fc60-11e7-8436-e7680fb4ec32.png">


Can you think of any other filtering options that should be added?

**Comment by Tonistroubles** [comment]
Then being able to filter on the following would probably do the trick:
- Seizoenen
- Upcoming
- Past
- Category
