### ISSUE TITLE
[wpt_events paginateby="category"] on home page broken

### ISSUE THREAD

**Issue by collingibson** [slimndap/wp-theatre#268]
Hi there. Thanks in advance for any help.

I manually added events on our 1) homepage page http://queenofthesquare.ca with category pagination and also on 2) http://queenofthesquare.ca/movies like this [wpt_events paginateby="category"] 

2) http://queenofthesquare.ca/movies works as expected but
1) http://queenofthesquare.ca throughs an error

example of category pagination tested on 2) that works: [ Featured Screening ]
this results in - http://queenofthesquare.ca/movies/featured-screening/
However the same category pagination tested on 1) results in - http://queenofthesquare.ca/?wpt_category=featured-screening

I can find know way to direct the pagination selection on the home page to work.
Am I missing something? Thanks

Collin

**Comment by slimndap** [comment]
I ran into this issue once before and was never able to fix it.

Workaround may be to create two pages:

1. The home pages with events but without category pagination, but with a Theater Categories widget in the sidebar.
2. A second page with events and category pagination. Set this page as the 'Page to show upcoming events on' in the Theater settings.

**Comment by collingibson** [comment]
Thanks @slimndap. Ill try that out.

**Comment by collingibson** [comment]
I went with just the widget and got where I wanted to go :) thanks @slimndap
