### ISSUE TITLE
PROJECT FOR SCHOOL

### ISSUE THREAD

**Issue by celttus** [slimndap/wp-theatre#289]
Hi i need som help, i dont know how to show the events in wordpress. I have created 1 but i dont know how to show it in my page to reserve locations.

Its for an school project if someone can help i will be so grateful!

Thanks!

**Comment by slimndap** [comment]
Hi @celttus!

You can show your events on your page by using one of the following shortcodes:
https://github.com/slimndap/wp-theatre/wiki/Shortcodes
