### ISSUE TITLE
Elementor post fields

### ISSUE THREAD

**Issue by lukefruin** [slimndap/wp-theatre#300]
Hi,
I use Elementor to build for Wordpress. I have a custom template for events but I'd like to be able to display more than just the basic post meta data dynamically. I'd like to have a button for tickets, for example. Does anyone have any idea how to do that?

**Comment by slimndap** [comment]
You can use this shortcode to display the event date and tickets button:

```
[wpt_production_events]
```

**Comment by lukefruin** [comment]
I have used the shortcode on the homepage, however I have built an Elementor template for event posts. I was wondering whether there was a way to place a dynamic ticket link within the post template itself.

**Comment by slimndap** [comment]
I am not an Elementor user. Isn't is possible to add some kind of shortcode
block to an Elementor template?
