### ISSUE TITLE
Some ideas that came up while using the plugin

### ISSUE THREAD

**Issue by paramir** [slimndap/wp-theatre#89]

**Comment by paramir** [comment]
first of all, thank you for this plugin! It was very useful in these last two projects Iv'e been working on:
http://viarudolphi.nl/
http://troubleman.nl/

While working and later from requests of the clients, these additions/improvements/features ideas came up:
- an option to list past events ($wp_theatre->events-> argument?)
- option for $production->dates() to show dates from the first date to last date (instead of next date to last date)
- sorting options for productions

**Comment by slimndap** [comment]
That look amazing! Thanks for sharing.

Most of your requests are already possible:

> an option to list past events ($wp_theatre->events-> argument?)

````
$args = array(
	'end' => 'now',	
);
$events = $wp_theatre->events->get($args);
````

> option for $production->dates() to show dates from the first date to last date (instead of next date to last date)

This requires a bit more code, but you can compile a list of all dates by using the list of events:

````
$dates = array();
foreach ($productions->events() as $event) {
	$dates[] = $event->date();
}
````

> sorting options for productions

Productions are always sorted by date, but you can change the sorting order like this:

````
$args = array(
	'order' => 'desc',	
);
echo $wp_theatre->production->get_html($args);
````

**Comment by slimndap** [comment]
After looking at the `$productions->dates()` method I agree that it can use some improvements. It was one of the first pieces of code in this plugin.

**Comment by paramir** [comment]
thank you!

the 'end' => 'now' argument is great! that is exactly what I needed :)

I ended up using something like that:

$dates = $production->events();
if( is_array($dates) && (count($dates)>0) && $dates[count($dates)-1]->datetime() > time() ){
	echo '<p class="info">' . $dates[0]->date() . ' t/m ' . $dates[count($dates)-1]->date() . '</p>';
}
the purpose of that is to show the show started running a while ago and is still playing.

thank you again :)

let me know if there is anything I can do for you!

ciao,
Ehud.

On 13 jan. 2015, at 20:36, Jeroen Schmit wrote:

That look amazing! Thanks for sharing.

Most of your requests are already possible:

an option to list past events ($wp_theatre->events-> argument?)

$args = array(
    'end' => 'now', 
);
$events = $wp_theatre->events->get($args);
option for $production->dates() to show dates from the first date to last date (instead of next date to last date)

This requires a bit more code, but you can compile a list of all dates by using the list of events:

$dates = array();
foreach ($productions->events() as $event) {
    $dates[] = $event->date();
}
sorting options for productions

Productions are always sorted by date, but you can change the sorting order like this:

$args = array(
    'order' => 'desc',  
);
echo $wp_theatre->production->get_html($args);

**Comment by slimndap** [comment]
> let me know if there is anything I can do for you!

Would you be interested in releasing an accompanying Theater theme on wordpress.org?

**Comment by paramir** [comment]
cool!
that would be very interesting :)
I'm in. 

where do we start?

On 13 jan. 2015, at 21:19, Jeroen Schmit wrote:

let me know if there is anything I can do for you!

Would you be interested in releasing an accompanying Theater theme on wordpress.org?
