### ISSUE TITLE
[wpt_events upcoming="true"] not working

### ISSUE THREAD

**Issue by PieterKruithof** [slimndap/wp-theatre#90]
Looks like the <code>[wpt_events upcoming="true"]</code> shortcode is not working.
Im using:
<code>
[wpt_events upcoming="true" paginateby="month" end="2016-1"] 
{{thumbnail|permalink}}
{{title|permalink}}
 {{date}}{{time}}
{{remark}}
[/wpt_events]
</code> (together with some html in between).
But the events are not filtered. On another page I'm using <code>[wpt_productions upcoming="true"]</code>what is working just fine...

Bug? Or am I missing something?

I'm on version 0.10.5 on this site: www.umai.nl

Thanks!

**Comment by slimndap** [comment]
Hi Peter!

You can fix this by changing the shortcode to:

`[wpt_events start="now" paginateby="month" end="2016-1"] {{thumbnail|permalink}} {{title|permalink}} {{date}}{{time}} {{remark}} [/wpt_events]`

The `upcoming` argument is deprecated. It still works, but you can't use it in combination with the `end` argument.

**Comment by PieterKruithof** [comment]
Ok, thanks! That works!

But somehow this is killing my proces. The site loadingtime is so much increased that it isn't loading anymore (live site). On my testsite this works, but slows down the site with 15 seconds...

Samething happened with the calendar widget. When activating this widget on a page, this increased the loadingtime of the page with 16 seconds. 
There are around 60 productions, with around 350 events in the database.

How can I speed this up? More seasons to split things up? Limit the output results? Paginate?

**Comment by slimndap** [comment]
I opened a new ticket for this one: #91.
